Allow exporting key material and init of cipherstate
flynn/noise pull request #50
Opened 2024-02-01 18:30 UTC by aidantwoods-1p

In order to allow implementations to store the nonce and key (e.g. for use with distributed systems), I've added an `UnsafeKey` method that exports the current key for storage. Combined with the `CipherSuite`, already exportable nonce, and this key, these can be used to reconstruct a `CipherState` from stored data using the new `UnsafeNewCipherState` method.

Noting that `UnsafeKey` isn't strictly necessary if it is already accessible from the `Cipher`, but I think this is preferable overall to needing to possibly create wrapped `Cipher` types which allow the key to be later exportable.

The `Unsafe` keyword is mean to indicate that these functions should be avoided at a glance, unless the caller accepts responsibility for manually managing exported state outside of application memory.

2024-02-01 19:04 UTC, titanous requested changes
This looks good, just minor nits in the docs.

2024-02-01 19:04 UTC, titanous commented on state.go
> +// UnsafeNewCipherState allows a CipherState to be reconstructed from exported components.
```suggestion
// UnsafeNewCipherState reconstructs a CipherState from exported components.
```

2024-02-01 19:04 UTC, titanous commented on state.go
> +// Note that it is important that, if resuming from exported state, then care is taken
```suggestion
// It is important that, when resuming from an exported state, care is taken
```

2024-02-01 19:04 UTC, titanous commented on state.go
> +// UnsafeKey returns the current value of k. This can be used to export the current key
```suggestion
// UnsafeKey returns the current value of k. This exports the current key
```

2024-02-02 00:36 UTC, aidantwoods-1p commented
Nits now resolved 🙂

2024-02-02 00:38 UTC, titanous approved these changes

2024-02-02 00:38 UTC, merged

2024-02-02 00:52 UTC, complexspaces commented
Thank you for taking a look at this so quick for us 🎉